# User query to Graph Schema attribute mapping
BUSSINESS_MAPPING = {
    "账簿": "Voucher.账簿",
    "期间": "Voucher.期间",
    "凭证": "Voucher",
    "凭证号": "Voucher.凭证号",
    "凭证摘要": "Voucher.凭证摘要",
    "凭证状态": "Voucher.状态",
    "应付账款": "Account(name=应付账款)",
    "应付职工薪酬": "Account(name=应付职工薪酬)",
    "数外凭证": ["Voucher.来源系统", "Voucher.来源类型"],
    "银行存款": "Account(name=银行存款)",
    "存款余额": ["Entry.借方", "Entry.贷方", "Account(name=银行存款)"],
    "客户": "Customer.name",
    "供应商": "Supplier.name",
    "部门": "Department.name",
    "员工": "Employee.name",
    "项目": "Project.name",
    "销售组": "SalesGroup.name",
    "费用项目": "ExpenseItem.name",
    "成本子项": "CostSubelement.name",
    "资产类别": "AssetCategory.name",
    "往来": ["Voucher-Entry", "FOR_CUSTOMER", "FOR_SUPPLIER", "FOR_OTHER_PARTY"],
    "余额": ["Entry.借方", "Entry.贷方"],
    "发生额": ["Entry.借方", "Entry.贷方"],
    "银行账户": "BankAccount",
    "现金账户": "CashAccount",
    "核算维度": ["Account", "其关联维度关系"],
}
