schema:
  indexes:
  - INDEX ON :凭证(人员编码)
  - INDEX ON :项目(项目编码)
  - INDEX ON :凭证(仓库编码)
  - INDEX ON :费用(编码)
  - INDEX ON :期间(名称)
  - INDEX ON :凭证(账簿)
  - INDEX ON :凭证(凭证id)
  - INDEX ON :产品线(产品线编码)
  - INDEX ON :客户(客户编码)
  - INDEX ON :供应商(编码)
  - INDEX ON :凭证(银行账号)
  - INDEX ON :科目(科目名称)
  - INDEX ON :人员(用户名)
  - INDEX ON :人员(工号)
  - INDEX ON :银行账户(银行账号)
  - INDEX ON :人员(人员id)
  - INDEX ON :仓库(编码)
  - INDEX ON :部门(部门编码)
  - INDEX ON :科目(编码)
  - INDEX ON :余额(fbalance_id)
  - INDEX ON :凭证(期间)
  - INDEX ON :凭证(客户编码)
  - INDEX ON :凭证(科目编码)
  - INDEX ON :凭证(供应商编码)
  - INDEX ON :凭证(费用编码)
  - INDEX ON :凭证(科目名称)
  - INDEX ON :账簿(名称)
  - INDEX ON :客户(客户名称)
  nodeLabels:
  - 银行账户
  - 凭证
  - 业务单元
  - 人员
  - 仓库
  - 供应商
  - 客户
  - 银行类别
  - 科目余额
  - 账簿
  - 期间
  - 科目
  - 部门
  - 余额
  - 费用
  - 产品线
  - 项目
  nodeProperties:
    业务单元:
    - 结算职能: string
    - 采购职能: string
    - 销售职能: string
    - 生产职能: string
    - 库存职能: string
    - 核算组织类型: string
    - 形态: string
    - 名称: string
    - 使用状态: string
    - 核算组织: string
    - 研发职能: string
    - uid: string
    - 编码: string
    - 质检职能: string
    - 收付职能: string
    - 资产职能: string
    - 税务职能: string
    - 资金职能: string
    产品线:
    - 产品线编码: string
    - demo: integer
    - 产品线名称: string
    人员:
    - 部门: string
    - 类型: string
    - 人员使用状态: string
    - 用户禁用: string
    - 职位: string
    - 兼职: string
    - uid: datetime
    - 手机号码: string
    - 性别: string
    - 序号: string
    - 用户名: string
    - 姓名: string
    - 工号: string
    - 负责人: string
    - 直接上级: string
    - 人员id: string
    - demo: string
    仓库:
    - 控制策略: string
    - 数据状态: string
    - 名称: string
    - 使用状态: string
    - 可发量控制: string
    - 创建组织: string
    - 编码: string
    - uid: string
    - 序号: string
    - 仓库负责人: string
    - 仓库id: string
    余额:
    - 本期发生额_贷方金额: integer
    - 期间: string
    - 科目名称: string
    - 账簿: string
    - 本期发生额_借方金额: integer
    - 期末余额_贷方金额: string
    - 第一维度编码: string
    - 期末余额.贷方金额: string
    - 本期发生额.贷方金额: string
    - 期末余额.借方金额: string
    - 本年累计.借方金额: string
    - 本期发生额.借方金额: string
    - 本年累计.贷方金额: string
    - fbalance_id: string
    - 时间: string
    - 基础资料属性: string
    - 科目编码: string
    - demo: string
    - 客户编码: string
    - 客户名称: string
    - 供应商名称: string
    - 供应商编码: string
    - 银行账户简称: string
    - 银行账号: string
    - 固定资产.累计折旧: string
    - 固定资产.净值: string
    - 固定资产.原值: string
    供应商:
    - 供应商状态: string
    - 原创建组织: string
    - 伙伴类型: string
    - 医药供应商属性: string
    - 使用状态: string
    - 数据状态: string
    - 编码: datetime
    - 名称: string
    - uid: datetime
    - 创建组织: string
    - 控制策略: string
    - 序号: string
    - 可VMI: string
    - 统一社会信用代码: string
    - 简称: string
    - 内部业务单元: string
    - 供应商id: string
    - demo: string
    凭证:
    - 核算维度_客户_名称: string
    - 审核日期: string
    - 核算维度_客户_编码: string
    - 创建时间: string
    - 修改时间: string
    - 来源类型: string
    - 业务日期: string
    - 过账人: string
    - 来源系统: string
    - 创建人: string
    - 制单人: string
    - 审核人: string
    - 审核驳回: string
    - 科目全名: string
    - 借方: string
    - 科目名称: string
    - 原币金额: string
    - 摘要: string
    - 科目编码: string
    - 币种: string
    - 凭证号: string
    - 状态: string
    - 过账: string
    - 记账日期: string
    - 凭证字: string
    - 科目_发生额方向: string
    - 账簿: string
    - uid: string
    - 序号: string
    - 期间: string
    - 贷方: string
    - 核算维度_银行_名称: string
    - 复核人: string
    - 核算维度_现金账户_账户名称: string
    - 核算维度_员工_工号: string
    - 核算维度_员工_姓名: string
    - 核算维度_部门_长名称: string
    - 核算维度_部门_编码: string
    - 到期日: string
    - 核算维度_物料_名称: string
    - 核算维度_资产类别_长名称: string
    - 核算维度_供应商_名称: string
    - 核算维度_供应商_编码: string
    - 凭证id: string
    - 部门: string
    - 客户名称: string
    - 供应商名称: string
    - demo: string
    - 供应商编码: string
    - 部门名称: string
    - 部门编码: string
    - 客户编码: string
    - 产品线名称: string
    - 产品线编码: string
    - 银行账号: string
    - 银行账户简称: string
    - 员工姓名: string
    - 员工工号: string
    - 项目名称: string
    - 项目编码: string
    - 费用类型: string
    - 附表项目: string
    - 附件数: string
    - 现金流量项目: string
    - 仓库编码: string
    - 人员编码: string
    - 费用编码: string
    客户:
    - 伙伴类型: string
    - 数据状态: string
    - 控制策略: string
    - uid: string
    - 序号: string
    - 创建组织: string
    - 业务职能: string
    - 客户编码: string
    - 可用状态: string
    - 医药客户属性: string
    - 客户名称: string
    - 客户id: string
    - demo: string
    期间:
    - 期数: integer
    - 名称: string
    - 年份: integer
    科目:
    - 科目编码: string
    - 科目名称: string
    - 名称: string
    - demo: string
    - 编码: string
    科目余额:
    - 期末余额_贷方金额: string
    - 科目名称: string
    - 基础资料属性: string
    - 科目编码: string
    - 年初余额_贷方金额: string
    - 期初余额_贷方金额: string
    - uid: string
    - 序号: string
    - 期间: string
    - 期初余额_借方金额: string
    - 期末余额_借方金额: string
    - 年初余额_借方金额: string
    - 本年累计_借方金额: string
    - 本期发生额_借方金额: string
    - 本期发生额_贷方金额: string
    - 本年累计_贷方金额: string
    账簿:
    - 名称: string
    费用:
    - 费用id: string
    - 编码: string
    - 名称: string
    部门:
    - 名称: string
    - demo: integer
    - 部门编码: string
    银行类别:
    - 行别代码: string
    - uid: string
    - 序号: string
    - 名称: string
    - 编码: string
    - 使用状态: string
    - 简码: string
    - 最后更新时间: string
    - 最后更新人: string
    银行账户:
    - 使用状态: string
    - 控制策略: string
    - 数据状态: string
    - 账户性质: string
    - 账户状态: string
    - 账户类型: string
    - 银行类别: string
    - 金融机构类别: string
    - 申请公司: string
    - 开户公司: string
    - 账户简称: string
    - 银行账号: string
    - uid: string
    - 最后更新人: string
    - 最后更新时间: string
    - 序号: string
    - 币别范围: string
    - 开户行: string
    - 银行账户id: string
    - demo: string
    项目:
    - 项目名称: string
    - demo: integer
    - 项目编码: string
  relationships:
  - relation: 制作了凭证
    source_labels:
    - 人员
    target_labels:
    - 凭证
  - relation: 银行交易
    source_labels:
    - 凭证
    target_labels:
    - 银行账户
  - relation: 有凭证记录
    source_labels:
    - 银行账户
    target_labels:
    - 凭证
  - relation: 采购往来
    source_labels:
    - 凭证
    target_labels:
    - 供应商
  - relation: 有业务凭证
    source_labels:
    - 供应商
    target_labels:
    - 凭证
  - relation: 凭证涉及客户
    source_labels:
    - 凭证
    target_labels:
    - 客户
  - relation: 客户被凭证涉及
    source_labels:
    - 客户
    target_labels:
    - 凭证
  - relation: 费用记账
    source_labels:
    - 凭证
    target_labels:
    - 费用
  - relation: 被凭证记录
    source_labels:
    - 费用
    target_labels:
    - 凭证
  - relation: 库存操作
    source_labels:
    - 凭证
    target_labels:
    - 仓库
  - relation: 有库存凭证
    source_labels:
    - 仓库
    target_labels:
    - 凭证
  - relation: 相关人员
    source_labels:
    - 凭证
    target_labels:
    - 人员
  - relation: 关联凭证
    source_labels:
    - 人员
    target_labels:
    - 凭证
  - relation: 审核了凭证
    source_labels:
    - 人员
    target_labels:
    - 凭证
  - relation: 凭证关联科目
    source_labels:
    - 凭证
    target_labels:
    - 科目
  - relation: 凭证关联账簿
    source_labels:
    - 凭证
    target_labels:
    - 账簿
  - relation: 凭证关联期间
    source_labels:
    - 凭证
    target_labels:
    - 期间
  - relation: 余额关联科目
    source_labels:
    - 科目余额
    target_labels:
    - 科目
  - relation: 余额关联账簿
    source_labels:
    - 余额
    target_labels:
    - 账簿
  - relation: 余额关联期间
    source_labels:
    - 余额
    target_labels:
    - 期间
  - relation: 由人员制单
    source_labels:
    - 凭证
    target_labels:
    - 人员
  - relation: 由人员审核
    source_labels:
    - 凭证
    target_labels:
    - 人员
  - relation: 期间关联余额
    source_labels:
    - 期间
    target_labels:
    - 余额
  - relation: 科目关联余额
    source_labels:
    - 科目
    target_labels:
    - 科目余额
  - relation: 账簿关联余额
    source_labels:
    - 账簿
    target_labels:
    - 余额
  - relation: 期间关联凭证
    source_labels:
    - 期间
    target_labels:
    - 凭证
  - relation: 科目关联凭证
    source_labels:
    - 科目
    target_labels:
    - 凭证
  - relation: 账簿关联凭证
    source_labels:
    - 账簿
    target_labels:
    - 凭证
