schema:
  indexes:
  - INDEX ON :业务单元(业务单元id)
  - INDEX ON :人员(人员id)
  - INDEX ON :供应商(供应商id)
  - INDEX ON :费用(费用id)
  - INDEX ON :凭证(凭证id)
  - INDEX ON :银行类别(银行类别id)
  - INDEX ON :客户(客户id)
  - INDEX ON :银行账户(银行账户id)
  - INDEX ON :余额(fbalance_id)
  - INDEX ON :仓库(仓库id)
  - INDEX ON :凭证(人员编码)
  - INDEX ON :项目(项目编码)
  - INDEX ON :凭证(仓库编码)
  - INDEX ON :费用(编码)
  - INDEX ON :产品线(产品线编码)
  - INDEX ON :客户(客户编码)
  - INDEX ON :供应商(编码)
  - INDEX ON :凭证(银行账号)
  - INDEX ON :人员(用户名)
  - INDEX ON :人员(工号)
  - INDEX ON :银行账户(银行账号)
  - INDEX ON :仓库(编码)
  - INDEX ON :部门(部门编码)
  - INDEX ON :科目(编码)
  - INDEX ON :余额(客户编码)
  - INDEX ON :凭证(银行账户编码)
  - INDEX ON :凭证(客户编码)
  - INDEX ON :余额(科目编码)
  - INDEX ON :凭证(科目编码)
  - INDEX ON :凭证(供应商编码)
  - INDEX ON :凭证(费用编码)
  - INDEX ON :余额(核算维度.客户编码)
  - INDEX ON :凭证(核算维度.客户编码)
  - CONSTRAINT 'UNIQUENESS' ON :业务单元(PROPERTY 业务单元id)
  - CONSTRAINT 'UNIQUENESS' ON :人员(PROPERTY 人员id)
  - CONSTRAINT 'UNIQUENESS' ON :供应商(PROPERTY 供应商id)
  - CONSTRAINT 'UNIQUENESS' ON :费用(PROPERTY 费用id)
  - CONSTRAINT 'UNIQUENESS' ON :凭证(PROPERTY 凭证id)
  - CONSTRAINT 'UNIQUENESS' ON :银行类别(PROPERTY 银行类别id)
  - CONSTRAINT 'UNIQUENESS' ON :客户(PROPERTY 客户id)
  - CONSTRAINT 'UNIQUENESS' ON :银行账户(PROPERTY 银行账户id)
  - CONSTRAINT 'UNIQUENESS' ON :余额(PROPERTY fbalance_id)
  - CONSTRAINT 'UNIQUENESS' ON :仓库(PROPERTY 仓库id)
  nodeLabels:
  - 人员
  - 仓库
  - 供应商
  - 客户
  - 银行账户
  - 业务单元
  - 费用
  - 银行类别
  - 凭证
  - 余额
  - 科目
  - 部门
  - 产品线
  - 项目
  nodeProperties:
    业务单元:
    - 编码: string
    - 名称: string
    - 使用状态: string
    - 形态: string
    - 资产职能: string
    - 核算组织: string
    - 采购职能: string
    - 库存职能: string
    - 结算职能: string
    - 销售职能: string
    - 收付职能: string
    - 质检职能: string
    - 生产职能: string
    - 研发职能: string
    - 业务单元id: string
    - 核算组织类型: string
    - 税务职能: string
    - 资金职能: string
    产品线:
    - 产品线编码: string
    - demo: integer
    - 产品线名称: string
    人员:
    - 用户名: string
    - 类型: string
    - 人员id: string
    - 工号: string
    - 人员使用状态: string
    - 姓名: string
    - 序号: string
    - 性别: string
    - 用户禁用: string
    - 手机号码: string
    - 负责人: string
    - 部门: string
    - 职位: string
    - 兼职: string
    - 直接上级: string
    - demo: string
    仓库:
    - 控制策略: string
    - 使用状态: string
    - 序号: string
    - 名称: string
    - 可发量控制: string
    - 创建组织: string
    - 仓库id: string
    - 编码: string
    - 仓库负责人: string
    余额:
    - 期间: string
    - 科目名称: string
    - 本期发生额.贷方金额: float
    - fbalance_id: string
    - 科目编码: string
    - 本年累计.借方金额: float
    - 期末余额.贷方金额: float
    - 本年累计.贷方金额: float
    - 时间: datetime
    - 序号: string
    - 基础资料属性: string
    - 本期发生额.借方金额: float
    - 期末余额.借方金额: float
    - 年初余额.贷方金额: string
    - 期初余额.贷方金额: string
    - 期初余额.借方金额: string
    - 账簿: string
    - demo: string
    - 客户编码: string
    - 客户名称: string
    - 供应商编码: string
    - 供应商名称: string
    - 银行账户简称: string
    - 银行账号: string
    - 固定资产.累计折旧: string
    - 固定资产.净值: string
    - 固定资产.原值: string
    供应商:
    - 医药供应商属性: string
    - 原创建组织: string
    - 供应商状态: string
    - 使用状态: string
    - 供应商id: datetime
    - 编码: datetime
    - 名称: string
    - 序号: string
    - 控制策略: string
    - 创建组织: string
    - 伙伴类型: string
    - 可VMI: string
    - 统一社会信用代码: string
    - 简称: string
    - 内部业务单元: string
    - demo: string
    凭证:
    - 科目名称: string
    - 修改人: string
    - 科目全名: string
    - 原币借方: string
    - 科目编码: string
    - 币种: string
    - 原币金额: float
    - 摘要: string
    - 借方: string
    - 凭证id: string
    - 附件数: float
    - 序号: string
    - 期间: string
    - 创建时间: datetime
    - 审核日期: datetime
    - 过账人: string
    - 来源系统: string
    - 借方合计: string
    - 修改时间: datetime
    - 创建人: string
    - 来源类型: string
    - 过账: string
    - 凭证摘要: string
    - 凭证字: string
    - 审核人: string
    - 记账日期: datetime
    - 状态: string
    - 凭证号: string
    - 账簿: string
    - 贷方合计: string
    - 制单人: string
    - 贷方: string
    - 原币贷方: string
    - 附表项目: string
    - 来源表单类型: string
    - 审核驳回: string
    - 核算维度.客户.编码: string
    - 核算维度.销售组.名称: string
    - 核算维度.客户.名称: string
    - 核算维度.供应商.名称: string
    - 复核人: string
    - 核算维度.部门.名称: string
    - 供应商编码: string
    - 费用编码: string
    - 仓库编码: string
    - 人员编码: string
    - 银行账号: string
    - 客户编码: string
    - 供应商名称: string
    - demo: string
    - 部门编码: string
    - 部门名称: string
    - 产品线编码: string
    - 客户名称: string
    - 产品线名称: string
    - 银行账户简称: string
    - 员工姓名: string
    - 员工工号: string
    - 项目编码: string
    - 项目名称: string
    - 费用类型: string
    - 现金流量项目: string
    客户:
    - 客户id: string
    - 业务职能: string
    - 控制策略: string
    - 客户名称: string
    - 客户编码: string
    - 可用状态: string
    - 伙伴类型: string
    - 序号: string
    - 医药客户属性: string
    - 创建组织: string
    - demo: string
    科目:
    - 编码: string
    - 名称: string
    - demo: string
    费用:
    - 是否叶子: string
    - 叶子: string
    - 名称: string
    - 关联单据: string
    - 编码: string
    - 使用状态: string
    - 控制策略: string
    - 费用id: string
    - 级次: string
    - 级次.1: string
    - 创建组织: string
    - 序号: string
    - 上级: string
    - 上级.编码: string
    部门:
    - demo: integer
    - 名称: string
    - 部门编码: string
    银行类别:
    - 最后更新时间: datetime
    - 使用状态: string
    - 序号: string
    - 名称: string
    - 最后更新人: string
    - 编码: string
    - 银行类别id: string
    - 行别代码: string
    - 简码: string
    银行账户:
    - 银行账户id: string
    - 账户状态: string
    - 使用状态: string
    - 控制策略: string
    - 账户性质: string
    - 申请公司: string
    - 序号: string
    - 最后更新时间: datetime
    - 账户类型: string
    - 最后更新人: string
    - 账户简称: string
    - 银行类别: string
    - 开户公司: string
    - 银行账号: string
    - 金融机构类别: string
    - 币别范围: string
    - 开户行: string
    - demo: string
    项目:
    - 项目名称: string
    - demo: integer
    - 项目编码: string
  relationships:
  - relation: 凭证涉及供应商
    source_labels:
    - 凭证
    target_labels:
    - 供应商
  - relation: 凭证涉及费用
    source_labels:
    - 凭证
    target_labels:
    - 费用
  - relation: 凭证涉及人员
    source_labels:
    - 凭证
    target_labels:
    - 人员
  - relation: 凭证涉及银行
    source_labels:
    - 凭证
    target_labels:
    - 银行账户
  - relation: 凭证涉及仓库
    source_labels:
    - 凭证
    target_labels:
    - 仓库
  - relation: 余额对应科目
    source_labels:
    - 余额
    target_labels:
    - 科目
  - relation: 余额对应客户
    source_labels:
    - 余额
    target_labels:
    - 客户
  - relation: 余额对应供应商
    source_labels:
    - 余额
    target_labels:
    - 供应商
  - relation: 凭证由人员制单
    source_labels:
    - 凭证
    target_labels:
    - 人员
  - relation: 凭证由人员审核
    source_labels:
    - 凭证
    target_labels:
    - 人员
  - relation: 凭证使用科目
    source_labels:
    - 凭证
    target_labels:
    - 科目
  - relation: 凭证涉及客户
    source_labels:
    - 凭证
    target_labels:
    - 客户
  - relation: 余额对应银行
    source_labels:
    - 余额
    target_labels:
    - 银行账户
  - relation: 余额对应人员
    source_labels:
    - 余额
    target_labels:
    - 人员
  - relation: 余额对应仓库
    source_labels:
    - 余额
    target_labels:
    - 仓库
  - relation: 余额对应费用
    source_labels:
    - 余额
    target_labels:
    - 费用
