schema:
  indexes:
  - INDEX ON :Account(account_code)
  - INDEX ON :Account(account_name)
  - INDEX ON :Account(account_type)
  - INDEX ON :Customer(customer_id)
  - INDEX ON :Customer(customer_name)
  - INDEX ON :Person(person_id)
  - INDEX ON :Person(person_name)
  - INDEX ON :Supplier(supplier_id)
  - INDEX ON :Supplier(supplier_name)
  - INDEX ON :VoucherEntry(credit_amount)
  - INDEX ON :VoucherEntry(debit_amount)
  - INDEX ON :VoucherEntry(entry_id)
  - INDEX ON :Voucher(voucher_date)
  - INDEX ON :Voucher(voucher_number)
  - INDEX ON :InventoryCategory(name)
  - INDEX ON :Supplier(name)
  - INDEX ON :CashAccount(name)
  - INDEX ON :BankAccount(name)
  - INDEX ON :SalesGroup(name)
  - INDEX ON :Employee(uid)
  - INDEX ON :Customer(uid)
  - INDEX ON :Customer(name)
  - INDEX ON :Voucher(voucher_id)
  - INDEX ON :VoucherEntry(uid)
  - INDEX ON :OtherParty(name)
  - INDEX ON :Account(code)
  - INDEX ON :CostSubelement(name)
  - INDEX ON :Entry(entry_id)
  - INDEX ON :Bank(name)
  - INDEX ON :Project(name)
  - INDEX ON :UseDepartment(name)
  - INDEX ON :AssetCategory(name)
  - INDEX ON :BusinessMode(name)
  - INDEX ON :Org(name)
  - INDEX ON :Employee(name)
  - INDEX ON :Department(name)
  - INDEX ON :ExpenseItem(name)
  - INDEX ON :AssetCard(name)
  - INDEX ON :Warehouse(name)
  - INDEX ON :ManualInput(name)
  - CONSTRAINT 'UNIQUENESS' ON :Account(PROPERTY account_code)
  - CONSTRAINT 'UNIQUENESS' ON :Customer(PROPERTY customer_id)
  - CONSTRAINT 'UNIQUENESS' ON :Person(PROPERTY person_id)
  - CONSTRAINT 'UNIQUENESS' ON :Supplier(PROPERTY supplier_id)
  - CONSTRAINT 'UNIQUENESS' ON :VoucherEntry(PROPERTY entry_id)
  - CONSTRAINT 'UNIQUENESS' ON :InventoryCategory(PROPERTY name)
  - CONSTRAINT 'UNIQUENESS' ON :Supplier(PROPERTY name)
  - CONSTRAINT 'UNIQUENESS' ON :CashAccount(PROPERTY name)
  - CONSTRAINT 'UNIQUENESS' ON :BankAccount(PROPERTY name)
  - CONSTRAINT 'UNIQUENESS' ON :SalesGroup(PROPERTY name)
  - CONSTRAINT 'UNIQUENESS' ON :Employee(PROPERTY uid)
  - CONSTRAINT 'UNIQUENESS' ON :Customer(PROPERTY uid)
  - CONSTRAINT 'UNIQUENESS' ON :Customer(PROPERTY name)
  - CONSTRAINT 'UNIQUENESS' ON :Voucher(PROPERTY voucher_id)
  - CONSTRAINT 'UNIQUENESS' ON :VoucherEntry(PROPERTY uid)
  - CONSTRAINT 'UNIQUENESS' ON :OtherParty(PROPERTY name)
  - CONSTRAINT 'UNIQUENESS' ON :Account(PROPERTY code)
  - CONSTRAINT 'UNIQUENESS' ON :CostSubelement(PROPERTY name)
  - CONSTRAINT 'UNIQUENESS' ON :Entry(PROPERTY entry_id)
  - CONSTRAINT 'UNIQUENESS' ON :Bank(PROPERTY name)
  - CONSTRAINT 'UNIQUENESS' ON :Project(PROPERTY name)
  - CONSTRAINT 'UNIQUENESS' ON :UseDepartment(PROPERTY name)
  - CONSTRAINT 'UNIQUENESS' ON :AssetCategory(PROPERTY name)
  - CONSTRAINT 'UNIQUENESS' ON :BusinessMode(PROPERTY name)
  - CONSTRAINT 'UNIQUENESS' ON :Org(PROPERTY name)
  - CONSTRAINT 'UNIQUENESS' ON :Employee(PROPERTY name)
  - CONSTRAINT 'UNIQUENESS' ON :Department(PROPERTY name)
  - CONSTRAINT 'UNIQUENESS' ON :ExpenseItem(PROPERTY name)
  - CONSTRAINT 'UNIQUENESS' ON :AssetCard(PROPERTY name)
  - CONSTRAINT 'UNIQUENESS' ON :Warehouse(PROPERTY name)
  - CONSTRAINT 'UNIQUENESS' ON :ManualInput(PROPERTY name)
  nodeLabels:
  - Person
  - Voucher
  - Entry
  - Account
  - SalesGroup
  - ExpenseItem
  - CostSubelement
  - AssetCategory
  - Warehouse
  - Customer
  - Project
  - ManualInput
  - Department
  - Supplier
  - OtherParty
  - Org
  - AssetCard
  - Bank
  - BusinessMode
  - Employee
  - InventoryCategory
  - BankAccount
  - UseDepartment
  - CashAccount
  - VoucherEntry
  nodeProperties:
    Account: []
    AssetCard: []
    AssetCategory: []
    Bank: []
    BankAccount: []
    BusinessMode: []
    CashAccount: []
    CostSubelement: []
    Customer: []
    Department: []
    Employee: []
    Entry: []
    ExpenseItem: []
    InventoryCategory: []
    ManualInput: []
    Org: []
    OtherParty: []
    Person: []
    Project: []
    SalesGroup: []
    Supplier: []
    UseDepartment: []
    Voucher: []
    VoucherEntry: []
    Warehouse: []
  relationships: []
