schema:
  indexes: []
  nodeLabels:
  - 凭证
  nodeProperties:
    凭证:
    - 核算维度_仓库_名称: string
    - 单价: string
    - 核算维度_客户_编码: string
    - 核算维度_客户_名称: string
    - 核算维度_仓库_编码: string
    - 审核驳回: string
    - 计量单位_编码: string
    - 计量单位_名称: string
    - 数量: string
    - 原币金额: float
    - 过账人: integer
    - AI记账: string
    - 核算维度_资产卡片_资产名称: string
    - 币种: string
    - 原币借方: string
    - 核算维度_存货类别_名称: string
    - 核算维度_成本子要素_名称: string
    - 核算维度_手工输入: string
    - 核算维度_经营方式_名称: string
    - 核算维度_项目_项目名称: string
    - 核算维度_资产使用部门_名称: string
    - 核算维度_销售组_名称: string
    - 核算维度_其他往来单位_名称: string
    - 核算维度_组织机构_名称: string
    - 核算维度_资产类别_名称: string
    - 核算维度_部门_名称: string
    - 核算维度_费用项目_长名称: string
    - 核算维度_银行账户_账户简称: string
    - 核算维度_现金账户_账户名称: string
    - 核算维度_供应商_名称: string
    - 核算维度_员工_姓名: string
    - 科目编码: string
    - 科目全名: string
    - 贷方合计: float
    - 摘要: string
    - 核算维度_银行_名称: string
    - 过账: string
    - 凭证摘要: string
    - 借方合计: float
    - 凭证字: integer
    - 凭证号: string
    - 状态: string
    - 序号: string
    - 账簿: integer
    - 期间: integer
    - 记账日期: string
    - uid: string
  relationships: []
